runtime: python311

instance_class: F1 # this is the cheapest option

# GCP commands used
# gcloud config set project cs348-guo549
# gcloud sql connect cs348-proj --user=root

env_variables:
  MYSQL_USER: root
  MYSQL_PASSWORD: ""
  MYSQL_DB: 'todo'
  MYSQL_HOST: 34.171.94.40

handlers:
- url: /img
  static_dir: static/img
  
- url: /script
  static_dir: static/script

- url: /styles
  static_dir: static/styles