INSERT INTO tasks (task, status, priority, duration) 
VALUES ("task no.1", "Todo", "High", 120),
       ("task no.2", "In Progress", "Medium", 240),
       ("task no.3", "Complete", "Low", 180),
       ("task no.4", "Todo", "High", 200),
       ("task no.5", "In Progress", "Medium", 220),
       ("task no.6", "Complete", "Low", 210),
       ("task no.7", "Todo", "High", 230),
       ("task no.8", "In Progress", "Medium", 250),
       ("task no.9", "Complete", "Low", 240),
       ("task no.10", "Todo", "High", 260),
       ("task no.11", "In Progress", "Medium", 270),
       ("task no.12", "Complete", "Low", 280),
       ("task no.13", "Todo", "High", 290),
       ("task no.14", "In Progress", "Medium", 300),
       ("task no.15", "Complete", "Low", 310),
       ("task no.16", "Todo", "High", 320),
       ("task no.17", "In Progress", "Medium", 330),
       ("task no.18", "Complete", "Low", 340),
       ("task no.19", "Todo", "High", 350),
       ("task no.20", "In Progress", "Medium", 360);